# Generated by Django 6.0.3 on 2026-03-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassifiedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("identity_document", "Identity Document"),
                            ("employment_contract", "Employment Contract"),
                            ("payslip", "Payslip"),
                            ("invoice", "Invoice"),
                            ("tax_form", "Tax Form"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("extracted_fields", models.JSONField(default=dict)),
                ("raw_text_preview", models.TextField(blank=True)),
                ("model_used", models.CharField(max_length=100)),
                ("processing_time_ms", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
